version: '3'
 
services:
  db:
    image: mysql:oracle
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
  app:
    image: tomwallyn/mspr-node:v0.0.3
    container_name: node_app
    links:
      - db
    restart: always
    ports:
      - 8060:4000
volumes:
  dbdata:
